# Generated by Django 5.2.9 on 2026-01-03 04:21

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_tag_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="banner",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=85,
                scale=None,
                size=[1200, 630],
                upload_to="articles/banners/",
            ),
        ),
    ]
